# fff
# COMMENT
title = "Расписание — неделя (2 дня)"

[[days]]
name = "Среда"
weekday = "Среда"

	[[days.events]]
	subject = "Информатика"
	type = "Лекция"
	start = "11:30"
	end = "13:00"
	teacher = "Балакшин Павел Валерьевич"
	location = "Актовый зал, ул. Ломоносова д.9"

	[[days.events]]
	subject = "Основы профессиональной деятельности"
	type = "Лекция"
	start = "13:30"
	end = "15:00"
	teacher = "Клименков Сергей Викторович"
	location = "Актовый зал, ул. Ломоносова д.9" # test comment  

[[days]]
name = "Суббота"
weekday = "Суббота"

	[[days.events]]
	subject = "Россия в истории современных международных отношений"
	type = "Консультация"
	start = "18:50"
	end = "20:20"
	teacher = "Богомазов Николай Иванович"
	location = ""

    [[days.events]]
	subject = "Велоспорт"
	type = "Спорт"
	start = "19:30"
	end = "21:30"
	teacher = "Тимофеев Андрей"
	location = "Тренажерный зал, Вяземский пер., д.5-7, лит.А"


	[[days.events]]
	subject = "Россия в истории современных международных отношений"
	type = "Консультация"
	start = "20:30"
	end = "22:00"
	teacher = "Богомазов Николай Иванович"
	location = ""

    
